### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by miko-ck** [solomonkinard/public#14]
I installed this extension in VSCode. How do I activate the blame view as shown in the picture on the extension page? I mean, the pictures are nice, but how do I get there?

I tried all the "blame" related options in the Ctrl+shift+p menu. They show various menus but not the main view I wanted. I found a sidebar on the left but there's nothing in it.

I found the 4 options in the context menu but they don't give me the normal blame view.

There's nothing in this repo's readme.

There's nothing on your website solomonkinard.com.

I literally tried everything I could. Please improve the documentation to make the extension usable.

**Comment by solomonkinard** [comment]
Does this [work](https://github.com/solomonkinard/public/issues/8) for you? That should probably be documented either way. If it doesn't work, can you share whether you're opening .md files, or any environment information? .md files probably don't have inline blame, which could also be documented. Thanks.

**Comment by miko-ck** [comment]
Hey Solomon,
Thanks for getting back to me so quickly. I figured out the blame was actually showing, just it was outside the viewport. I had to scroll right to see it. Which is still not great, but better than nothing. I eventually found another extension that has more controls (in particular, can show blame on the left, just like git)
Cheers,
Miko

From: Solomon Kinard ***@***.***>
Date: Tuesday, 18. June 2024 at 02:30
To: solomonkinard/public ***@***.***>
Cc: Miko Dadela ***@***.***>, Author ***@***.***>
Subject: Re: [solomonkinard/public] How to use this extension? (Issue #14)

Does this work<https://github.com/solomonkinard/public/issues/8> for you? That should probably be documented either way. If it doesn't work, can you share whether you're opening .md files, or any environment information? .md files probably don't have inline blame, which could also be documented. Thanks.

**Comment by bb-soat** [comment]
On my side, I had to downgrade to V0.2.21 because latest version does not work anymore.

**Comment by solomonkinard** [comment]
Thanks for sharing. It hasn't been updated in the last few weeks. What didn't work for you then?

**Comment by bb-soat** [comment]
From v0.2.22, the "Show Blame Inline" does not work

**Comment by solomonkinard** [comment]
Agreed that v0.2.21 is stable; it's the recommended version for anyone looking for stability. The next version introduced a [ton of changes](https://github.com/solomonkinard/public/issues/15) from open issues and beyond. To help debug your issue, consider sharing more specifics, like if the [setting is enabled](https://github.com/solomonkinard/public/issues/8) and the OS. This seems to be working on Mac. However, there are several known and unknown problems. Opening new issues with specific details helps a lot for triaging and prioritization.

**Comment by solomonkinard** [comment]
* This bug was opened as "how to use this extension", which is a general question. [Answered](https://docs.google.com/document/d/1f4m3AgV6VlNb5ZM42tKmN1Mt55mMWoOi0oEllZG-eTM).
* Comments about documentation have been resolved by adding a "> Git Blame: Help" command.
* Comments about inline blame not being visible were resolved by stating that they are on the right.
* Comments about "Show Blame Inline" did not provide any specifics, but a fix as a guess was published anyway in [v0.2.32](https://docs.google.com/document/d/1ITcUnMiDDaSk-4PMhXIIJCwcwqN0IwZmRhznN9sE14w).

Closing this bug now. It's unclear if your issue is resolved without specifics, even though a potential fix was published. Instead of leaving this bug open for people to find, I put a summary of parts of this thread in the README. Anyone can open a new issue if there is something specific that they'd like to be addressed. General complaints are also welcome. The more the merrier.
