### ISSUE TITLE
Extension source code

### ISSUE THREAD

**Issue by Dancheg97** [solomonkinard/public#7]
Hello!
I was looking for [this extension](https://open-vsx.org/extension/solomonkinard/git-search) source code. The VSX Registry points to this repository, but in reality, there is no extension source code in this repo.
I just wanted to clarify if there is a chance to see the source code.

**Comment by T1mL3arn** [comment]
So, this is closed-source?

**Comment by Dancheg97** [comment]
> So, this is closed-source?

Seems like so...

**Comment by solomonkinard** [comment]
There's a newer version that extension and its source code is [here](http://vsixlens.com/?id=solomonkinard.git-blame). I built this source code viewer for any VS Code extension. Just use the item name of your choice for the id, for example http://vsixlens.com/?id=solomonkinard.git-blame. This seems like the better option to me because it shows the actual code that's running, instead of a possible mismatch between source code and actual production.

**Comment by solomonkinard** [comment]
There's a newer version of that extension and its source code is [here](http://vsixlens.com/?id=solomonkinard.git-blame). I built this source code viewer for any VS Code extension. Just use the item name of your choice for the id, for example http://vsixlens.com/?id=solomonkinard.git-blame. This seems like the better option to me because it shows the actual code that's running, instead of a possible mismatch between source code and actual production.
